package com.forex.test.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CurrentExchangeRatesJsonRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurrentExchangeRatesJsonRequestAllPropertiesEquals(
        CurrentExchangeRatesJsonRequest expected,
        CurrentExchangeRatesJsonRequest actual
    ) {
        assertCurrentExchangeRatesJsonRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertCurrentExchangeRatesJsonRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurrentExchangeRatesJsonRequestAllUpdatablePropertiesEquals(
        CurrentExchangeRatesJsonRequest expected,
        CurrentExchangeRatesJsonRequest actual
    ) {
        assertCurrentExchangeRatesJsonRequestUpdatableFieldsEquals(expected, actual);
        assertCurrentExchangeRatesJsonRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurrentExchangeRatesJsonRequestAutoGeneratedPropertiesEquals(
        CurrentExchangeRatesJsonRequest expected,
        CurrentExchangeRatesJsonRequest actual
    ) {
        assertThat(expected)
            .as("Verify CurrentExchangeRatesJsonRequest auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurrentExchangeRatesJsonRequestUpdatableFieldsEquals(
        CurrentExchangeRatesJsonRequest expected,
        CurrentExchangeRatesJsonRequest actual
    ) {
        assertThat(expected)
            .as("Verify CurrentExchangeRatesJsonRequest relevant properties")
            .satisfies(e -> assertThat(e.getRequestId()).as("check requestId").isEqualTo(actual.getRequestId()))
            .satisfies(e -> assertThat(e.getTimestamp()).as("check timestamp").isEqualTo(actual.getTimestamp()))
            .satisfies(e -> assertThat(e.getClient()).as("check client").isEqualTo(actual.getClient()))
            .satisfies(e -> assertThat(e.getCurrency()).as("check currency").isEqualTo(actual.getCurrency()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurrentExchangeRatesJsonRequestUpdatableRelationshipsEquals(
        CurrentExchangeRatesJsonRequest expected,
        CurrentExchangeRatesJsonRequest actual
    ) {}
}
