package com.forex.test.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HistoryExchangeRatesJsonRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoryExchangeRatesJsonRequestAllPropertiesEquals(
        HistoryExchangeRatesJsonRequest expected,
        HistoryExchangeRatesJsonRequest actual
    ) {
        assertHistoryExchangeRatesJsonRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertHistoryExchangeRatesJsonRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoryExchangeRatesJsonRequestAllUpdatablePropertiesEquals(
        HistoryExchangeRatesJsonRequest expected,
        HistoryExchangeRatesJsonRequest actual
    ) {
        assertHistoryExchangeRatesJsonRequestUpdatableFieldsEquals(expected, actual);
        assertHistoryExchangeRatesJsonRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoryExchangeRatesJsonRequestAutoGeneratedPropertiesEquals(
        HistoryExchangeRatesJsonRequest expected,
        HistoryExchangeRatesJsonRequest actual
    ) {
        assertThat(expected)
            .as("Verify HistoryExchangeRatesJsonRequest auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoryExchangeRatesJsonRequestUpdatableFieldsEquals(
        HistoryExchangeRatesJsonRequest expected,
        HistoryExchangeRatesJsonRequest actual
    ) {
        assertThat(expected)
            .as("Verify HistoryExchangeRatesJsonRequest relevant properties")
            .satisfies(e -> assertThat(e.getRequestId()).as("check requestId").isEqualTo(actual.getRequestId()))
            .satisfies(e -> assertThat(e.getTimestamp()).as("check timestamp").isEqualTo(actual.getTimestamp()))
            .satisfies(e -> assertThat(e.getClient()).as("check client").isEqualTo(actual.getClient()))
            .satisfies(e -> assertThat(e.getCurrency()).as("check currency").isEqualTo(actual.getCurrency()))
            .satisfies(e -> assertThat(e.getPeriod()).as("check period").isEqualTo(actual.getPeriod()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoryExchangeRatesJsonRequestUpdatableRelationshipsEquals(
        HistoryExchangeRatesJsonRequest expected,
        HistoryExchangeRatesJsonRequest actual
    ) {}
}
